            </div><!-- .content-wrapper -->
        </div><!-- .layout-content -->
    </div><!-- .layout -->

    <!-- Table of Contents (right panel) - auto-generated by JS -->
    <aside class="toc" id="toc"></aside>

    <footer class="footer">
        <p>LD TechLab Programming Tutorials &mdash; Created by Mr. Lloyd Christopher F. Dacles, MIS</p>
        <p style="margin-top:6px;"><a href="/status">System Status</a></p>
    </footer>
    <script src="/js/app.js"></script>
</body>
</html>
